!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  fixed_frame: vlp16_04
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      fixed_frame: vlp16_04
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_range: 130.0
      min_range: 0.4
      name: Default
      organize_cloud: false
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      target_frame: vlp16_04
      type: ''
      view_direction: 0.0
      view_width: 3.5185837720208
    state: []
  max_range: 130.0
  min_range: 0.4
  organize_cloud: false
  target_frame: vlp16_04
  view_direction: 0.0
  view_width: 3.5185837720208
state: []
